/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IRiskAssessmentInterface extends Interface {
  getFunction(
    nameOrSignature: "assessVehicle" | "calculatePremium"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "assessVehicle",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePremium",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "assessVehicle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePremium",
    data: BytesLike
  ): Result;
}

export interface IRiskAssessment extends BaseContract {
  connect(runner?: ContractRunner | null): IRiskAssessment;
  waitForDeployment(): Promise<this>;

  interface: IRiskAssessmentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assessVehicle: TypedContractMethod<
    [
      _regPlate: string,
      _baseValue: BigNumberish,
      _age: BigNumberish,
      _mileage: BigNumberish,
      _condition: BigNumberish,
      _hasAccidentHistory: boolean
    ],
    [[bigint, bigint]],
    "nonpayable"
  >;

  calculatePremium: TypedContractMethod<
    [_regPlate: string, _tier: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assessVehicle"
  ): TypedContractMethod<
    [
      _regPlate: string,
      _baseValue: BigNumberish,
      _age: BigNumberish,
      _mileage: BigNumberish,
      _condition: BigNumberish,
      _hasAccidentHistory: boolean
    ],
    [[bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculatePremium"
  ): TypedContractMethod<
    [_regPlate: string, _tier: BigNumberish],
    [bigint],
    "view"
  >;

  filters: {};
}
