/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iVehicleShieldSol from "./IVehicleShield.sol";
export { InsuranceCore__factory } from "./InsuranceCore__factory";
export { PolicyNFT__factory } from "./PolicyNFT__factory";
export { RiskAssessment__factory } from "./RiskAssessment__factory";
