/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPolicyNFT__factory } from "./IPolicyNFT__factory";
export { IRiskAssessment__factory } from "./IRiskAssessment__factory";
