/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRiskAssessment,
  IRiskAssessmentInterface,
} from "../../../contracts/IVehicleShield.sol/IRiskAssessment";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_regPlate",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_baseValue",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_age",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_mileage",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "_condition",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "_hasAccidentHistory",
        type: "bool",
      },
    ],
    name: "assessVehicle",
    outputs: [
      {
        internalType: "enum IVehicleShield.VerificationTier",
        name: "",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_regPlate",
        type: "string",
      },
      {
        internalType: "enum IVehicleShield.VerificationTier",
        name: "_tier",
        type: "uint8",
      },
    ],
    name: "calculatePremium",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRiskAssessment__factory {
  static readonly abi = _abi;
  static createInterface(): IRiskAssessmentInterface {
    return new Interface(_abi) as IRiskAssessmentInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRiskAssessment {
    return new Contract(address, _abi, runner) as unknown as IRiskAssessment;
  }
}
