/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iVehicleShieldSol from "./IVehicleShield.sol";
export type { iVehicleShieldSol };
export type { InsuranceCore } from "./InsuranceCore";
export type { PolicyNFT } from "./PolicyNFT";
export type { RiskAssessment } from "./RiskAssessment";
